### ISSUE TITLE
The profile name in the output includes the NetworkManager filename extension

### ISSUE THREAD

**Issue by SebastianStork** [Janik-Haag/nm2nix#1]
First Issue 🎉😁

First of all, thanks for the script. It saved me so much time. 

I ran the provided command and got this output
```
{
    Fairphone4.nmconnection = {
        ...
    };
    ...
};
```

and pasted the output into my nixos-config but got this (somewhat nonsensical) error during nixos-rebuild
```
error: The option `networking.networkmanager.ensureProfiles.profiles.Fairphone4.connection.type' is used but not defined.
```

I fixed it by removing the `.nmconnection` filename extension from the wifi name
`Fairphone4.nmconnection = {` -> `Fairphone4 = {`

The `.nmconnection` should probably be automatically removed.

**Comment by Janik-Haag** [comment]
glad to see it helps some people.
fixed it, I should probably have done that earlier :)
iirc I just used nvim's search and replace.

in some cases you will have to do manual escaping, wrapping the key like `networking.networkmanager.ensureProfiles.profiles."Fairphone4" = {};` should be enough in most cases
